use crate::storage;
use soroban_sdk::{contracterror, contracttype, Address, BytesN, Env, IntoVal, TryFromVal, Val};

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Error {
    OnlyOwner = 1,
    OnlyOracle = 2,
}

#[contracttype]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ProposalStatus {
    Canceled = 0,
    Actived = 1,
    Picked = 2,
}

#[contracttype]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum SignatureStatus {
    Canceled = 0,
    Actived = 1,
    Picked = 2,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EscrowProposal {
    /**
     * Specific ID generated by the User proposal
     */
    pub id: BytesN<32>,
    /**
     * Current status of the proposal
     */
    pub status: ProposalStatus,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SignatureTxEscrow {
    /**
     * The transaction escrow ID is the signature ID from Signaturit.
     * It is an UUID (36 bytes length), for example: '6f6c974e-2910-11e4-b3d4-0aa7697eb409'
     */
    pub id: BytesN<36>,
    pub seller: Address,
    pub receiver: Address,
}

#[contracttype]
pub enum DataKey {
    Proposal(BytesN<32>),
}

impl storage::Storage for DataKey {
    fn get<V: TryFromVal<Env, Val>>(&self, env: &Env) -> Option<V> {
        match self {
            DataKey::Proposal(_) => storage::Persistent::get(env, self),
        }
    }

    fn set<V: IntoVal<Env, Val>>(&self, env: &Env, val: &V) {
        match self {
            DataKey::Proposal(_) => storage::Persistent::set(env, self, val),
        }
    }

    fn has(&self, env: &Env) -> bool {
        match self {
            DataKey::Proposal(_) => storage::Persistent::has(env, self),
        }
    }

    fn extend(&self, env: &Env, min_ledger_to_live: u32) -> &Self {
        if !self.has(env) {
            return self;
        }

        match self {
            DataKey::Proposal(_) => storage::Persistent::extend(env, self, min_ledger_to_live),
        };
        self
    }

    fn remove(&self, env: &Env) {
        match self {
            DataKey::Proposal(_) => storage::Persistent::remove(env, self),
        }
    }
}
