use crate::storage;
use soroban_sdk::{
    contracterror, contracttype, Address, BytesN, Env, IntoVal, String, TryFromVal, Val,
};

#[contracttype]
pub enum DataKey {
    ProposalCounter,
    Proposal(u32),
}

impl storage::Storage for DataKey {
    fn get<V: TryFromVal<Env, Val>>(&self, env: &Env) -> Option<V> {
        match self {
            DataKey::Proposal(_) | DataKey::ProposalCounter => storage::Persistent::get(env, self),
        }
    }

    fn set<V: IntoVal<Env, Val>>(&self, env: &Env, val: &V) {
        match self {
            DataKey::Proposal(_) | DataKey::ProposalCounter => {
                storage::Persistent::set(env, self, val)
            }
        }
    }

    fn has(&self, env: &Env) -> bool {
        match self {
            DataKey::Proposal(_) | DataKey::ProposalCounter => storage::Persistent::has(env, self),
        }
    }

    fn extend(&self, env: &Env, min_ledger_to_live: u32) -> &Self {
        if !self.has(env) {
            return self;
        }

        match self {
            DataKey::Proposal(_) | DataKey::ProposalCounter => {
                storage::Persistent::extend(env, self, min_ledger_to_live)
            }
        };
        self
    }

    fn remove(&self, env: &Env) {
        match self {
            DataKey::Proposal(_) | DataKey::ProposalCounter => {
                storage::Persistent::remove(env, self)
            }
        }
    }
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EscrowProposal {
    /**
    Specific ID generated by the Escrow
     */
    pub escrow_id: u32,
    /**
    Proposal ID from stocken, so can know what is the propose
     */
    pub stocken_proposal_id: String,

    /**
    Current status of the proposal
     */
    pub status: ProposalStatus,

    /**
    Owner of the proposal, who will receive the fund after success
     */
    pub owner: Address,
}

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum EscrowError {
    OnlyOwner = 1,
    OnlyOracle = 2,
    AlreadyProposed = 3,
    ProposalNotFound = 4,
}

#[contracttype]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ProposalStatus {
    Canceled = 0,
    Actived = 1,
    Picked = 2,
}

#[contracttype]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum SignatureStatus {
    Canceled = 0,
    Actived = 1,
    Picked = 2,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SignatureTxEscrow {
    /**
     * The transaction escrow ID is the signature ID from Signaturit.
     * It is an UUID (36 bytes length), for example: '6f6c974e-2910-11e4-b3d4-0aa7697eb409'
     */
    pub id: BytesN<36>,
    pub seller: Address,
    pub receiver: Address,
}
