name: Tests CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install soroban-cli
        run: cargo install soroban-cli --features opt

      - name: Build the contract
        run: make -C contracts build

      - name: Run the test
        run: make -C contracts test
