name: Tests CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Build NFT Notes
        working-directory: ./contracts/notes_nft
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Build Signaturit Oracle
        working-directory: ./contracts/signaturit_oracle
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Build Escrow test
        working-directory: ./contracts/escrow_test
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Build Escrow
        working-directory: ./contracts/escrow
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Run tests
        run: cargo test

      # - name: Run tests
      #   run: cargo build --target wasm32-unknown-unknown --release ; cargo build --target wasm32-unknown-unknown --release ; cargo test
